version: "3.8"
services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    env_file:
      - .env
    environment:
      - N8N_ENCRYPTION_KEY=your_strong_random_key
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=your_username
      - N8N_BASIC_AUTH_PASSWORD=your_password
    volumes:
      - ./n8n_data:/home/node/.n8n
    restart: unless-stopped
